services:
  idp:
    container_name: Infra.Modules.IdentityProvider
    build:
      context: ./Modules/IdentityProvider
      dockerfile: Dockerfile
    volumes:
      - ./Proxy/Nginx/certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=${IDP_SERVER_URLS}
      - IDP_CONNECTION_STRING=${IDP_CONNECTION_STRING}
      - COMPANY_NAME=${COMPANY_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - IDP_ACC_PANEL_URL=${IDP_ACC_PANEL_URL}
      - IDP_ACC_PANEL_SCOPES=${IDP_ACC_PANEL_SCOPES}
      - IDP_ISSUER=${IDP_ISSUER}
      - IDP_ACC_PANEL_CLIENT_DISPLAY_NAME=${IDP_ACC_PANEL_CLIENT_DISPLAY_NAME}
      - IDP_ACC_PANEL_CLIENT_SECRET=${IDP_ACC_PANEL_CLIENT_SECRET}
      - IDP_ACC_PANEL_REDIRECT_URI=${IDP_ACC_PANEL_REDIRECT_URI}
      - IDP_ACC_PANEL_POST_LOGOUT_REDIRECT_URI=${IDP_ACC_PANEL_POST_LOGOUT_REDIRECT_URI}
    depends_on:
      - idp_postgres
      - idp_redis
    networks:
      Infra.Proxy.Network:
        aliases:
          - identity.assts.tech

  idp_postgres:
    container_name: Infra.Modules.IdentityProvider.Postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - idp_postgres_data:/var/lib/postgresql/data
  
  idp_redis:
    container_name: Infra.Modules.IdentityProvider.Redis
    image: redis:7-alpine
    restart: always
    volumes:
      - idp_redis_data:/data
  
  acc_panel:
    container_name: Infra.Modules.AccountPanel
    build:
      context: ./Modules/AccountPanel
      dockerfile: Dockerfile
    volumes:
      - ./Proxy/Nginx/certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=${ACCOUNTING_PANEL_SERVER_URLS}
      - IDP_SERVER_URL=${IDP_SERVER_URL}
      - COMPANY_NAME=${COMPANY_NAME}
      - IDP_ACC_PANEL_URL=${IDP_ACC_PANEL_URL}
      - IDP_ACC_PANEL_SCOPES=${IDP_ACC_PANEL_SCOPES}
      - IDP_ISSUER=${IDP_ISSUER}
      - IDP_ACC_PANEL_CLIENT_DISPLAY_NAME=${IDP_ACC_PANEL_CLIENT_DISPLAY_NAME}
      - IDP_ACC_PANEL_CLIENT_SECRET=${IDP_ACC_PANEL_CLIENT_SECRET}
      - IDP_ACC_PANEL_REDIRECT_URI=${IDP_ACC_PANEL_REDIRECT_URI}
      - IDP_ACC_PANEL_POST_LOGOUT_REDIRECT_URI=${IDP_ACC_PANEL_POST_LOGOUT_REDIRECT_URI}
    depends_on:
      - idp
    networks:
      Infra.Proxy.Network:
        aliases:
          - account.assts.tech

  proxy_nginx:
    container_name: Infra.Proxy.Nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Proxy/Nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Proxy/Nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - idp
    networks:
      Infra.Proxy.Network:

volumes:
  idp_postgres_data:
  idp_redis_data:

networks:
  Infra.Proxy.Network:
    driver: bridge