services:
  idp:
    container_name: Infra.Modules.IdentityProvider
    build:
      context: ./Modules/IdentityProvider
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=${IDP_SERVER_URLS}
      - IDP_CONNECTION_STRING=${IDP_CONNECTION_STRING}
      - COMPANY_NAME=${COMPANY_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
    depends_on:
      - idp_postgres
      - idp_redis

  idp_postgres:
    container_name: Infra.Modules.IdentityProvider.Postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - idp_postgres_data:/var/lib/postgresql/data
  
  idp_redis:
    container_name: Infra.Modules.IdentityProvider.Redis
    image: redis:7-alpine
    restart: always
    volumes:
      - idp_redis_data:/data
  
  proxy_nginx:
    container_name: Infra.Proxy.Nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Proxy/Nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Proxy/Nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - idp

volumes:
  idp_postgres_data:
  idp_redis_data: