services:
  idp:
    container_name: Infra.Modules.IdentityProvider.Dev
    build:
      context: ./Modules/IdentityProvider
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/asststech.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devpass
    volumes:
      - ./Modules/IdentityProvider/Pages:/src/Pages
      - ./Modules/IdentityProvider/Data:/src/Data
      - ./Modules/IdentityProvider/Program.cs:/src/Program.cs
      - ./Modules/IdentityProvider/wwwroot:/src/wwwroot
      - /tmp/NuGetScratch:/tmp/NuGetScratch
      - ./Platform/Nginx/certs/asststech.pfx:/https/asststech.pfx:ro
    depends_on:
      - idp_postgres
      - idp_redis
  
  commerce:
    build:
      context: ./Modules/Commerce
      dockerfile: Dockerfile.dev
    container_name: Infra.Modules.Commerce.Dev
    env_file:
      - .env
    environment:
      PGSSLMODE: disable
    volumes:
      - ./Modules/Commerce/medusa-config.ts:/app/medusa-config.ts
      - ./Modules/Commerce/src:/app/src
      - ./Platform/Nginx/certs:/app/certs:ro
    command: >
      sh -c '
        echo "ENVIRONMENT=${ENVIRONMENT}"  > .env &&
        echo "DATABASE_URL=${COMMERCE_DATABASE_URL}" >> .env &&
        yarn migrations -- --db commerce_db --no-interactive &&
        rm .env &&
        yarn dev
      '
  
  acc_panel:
    container_name: Infra.Modules.AccountPanel.Dev
    build:
      context: ./Modules/AccountPanel
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/asststech.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devpass
    volumes:
      - ./Modules/AccountPanel/Pages:/src/Pages
      - ./Modules/AccountPanel/Program.cs:/src/Program.cs
      - ./Modules/AccountPanel/wwwroot:/src/wwwroot
      - /tmp/NuGetScratch:/tmp/NuGetScratch
      - ./Platform/Nginx/certs/asststech.pfx:/https/asststech.pfx:ro
    depends_on:
      - idp_postgres
      - idp_redis
